### ISSUE TITLE
Where are the unit tests?

### ISSUE THREAD

**Issue by TheAngryByrd** [gregoryyoung/nothing#6]
I know this is a small framework in all, but where are the unit tests?  It even has unit as the name!

**Comment by bartelink** [comment]
Again, please don't just flip-flop; this is a long-standing concern in the `nothing` community. Rather than [signalling assent by this waton destruction](https://blog.jessfraz.com/post/the-art-of-closing/), I'd like to suggest you reconsider and perhaps double down by demanding it has acceptance tests, like a core fundamental block should.
